const LANGUAGE_MAP = {
	js: 'javascript',
	mjs: 'javascript',
	cjs: 'javascript',
	jsx: 'jsx',
	ts: 'typescript',
	tsx: 'tsx',
	py: 'python',
	rb: 'ruby',
	java: 'java',
	go: 'go',
	rs: 'rust',
	c: 'c',
	cpp: 'cpp',
	h: 'c',
	hpp: 'cpp',
	cs: 'csharp',
	php: 'php',
	swift: 'swift',
	kt: 'kotlin',
	scala: 'scala',
	r: 'r',
	lua: 'lua',
	vim: 'vim',
	dockerfile: 'docker',
	makefile: 'makefile',
	toml: 'toml',
	ini: 'ini',
	xml: 'xml',
	txt: 'text',
	html: 'html',
	htm: 'html',
	css: 'css',
	scss: 'scss',
	less: 'less',
	json: 'json',
	yaml: 'yaml',
	yml: 'yaml',
	sql: 'sql',
	graphql: 'graphql',
	gql: 'graphql',
	sh: 'bash',
	bash: 'bash',
	zsh: 'bash',
	fish: 'bash',
	ps1: 'powershell',
	tf: 'hcl',
	pl: 'perl',
	ex: 'elixir',
	exs: 'elixir',
	erl: 'erlang',
	hs: 'haskell',
};

export const getFileLanguage = (filename) => {
	if (!filename) return 'text';
	const ext = filename.split('.').pop().toLowerCase();
	return LANGUAGE_MAP[ext] || 'text';
};

export const isMarkdownFile = (filename) => /\.(md|markdown|mdx)$/i.test(filename || '');
